function y = aceleracao(u, start, tRise, tFall, duration, amplitude)
    y = (heaviside(u - start) - heaviside(u- (start+tRise) ))*amplitude.*((u-start)/tRise).^2 + ...
        (heaviside(u - (start+tRise)) - heaviside(u- (start+tRise+duration) ))*amplitude + ...
        (heaviside(u - (start+tRise+duration) ) - heaviside(u- (start+tRise+duration+tFall) ))*amplitude.*(1-((u- (start+tRise+duration) )/tFall).^2);
end